export const MAPBOX_PUBLIC_KEY =
  'pk.eyJ1IjoibGx1biIsImEiOiJja2FqN2k2djIwNDU5MnlvNjR4YXRrMzFsIn0.Oir7SYHkVKBlgbPHldtRGQ'
export const NETHERLANDS_ALBUM_TOKEN = 'B125ON9t3mbLNC'
export const SINGAPORE_ALBUM_TOKEN = 'B12GqkRUiGojvkQ'

export const APENHEUL_ALBUM_TOKEN = 'B12Gf693ZB46qE'
export const AVIODROME_ALBUM_TOKEN = 'B12GDdyTvGr3NKR'
export const BELGIË_ALBUM_TOKEN = 'B125idkMw63OJI'
export const FLORIADE_2022_ALBUM_TOKEN = 'B12GFssfGGlnbYK'
export const JOE_HISAISHI_2020_ALBUM_TOKEN = 'B12GQOeMmJFtTid'
export const KEUKENHOF_ALBUM_TOKEN = 'B12JEsNWnGLyCMW'
export const SEA_AQUARIUM_2022_ALBUM_TOKEN = 'B12GRMtznG48SWT'
export const SINGAPORE_BIRDS_2020 = 'B125aVbMKGt3yAq'
export const SINGAPORE_FOREST_HIKE_2021_ALBUM_TOKEN = 'B12GdIshaGxfr5E'
export const TEXEL_DENHELDER_2022_ALBUM_TOKEN = 'B125GH8MqRX4Fb'

export const ALLOW_TOKEN_IDS = [
  NETHERLANDS_ALBUM_TOKEN,
  SINGAPORE_ALBUM_TOKEN,
  APENHEUL_ALBUM_TOKEN,
  AVIODROME_ALBUM_TOKEN,
  BELGIË_ALBUM_TOKEN,
  FLORIADE_2022_ALBUM_TOKEN,
  JOE_HISAISHI_2020_ALBUM_TOKEN,
  KEUKENHOF_ALBUM_TOKEN,
  SEA_AQUARIUM_2022_ALBUM_TOKEN,
  SINGAPORE_BIRDS_2020,
  SINGAPORE_FOREST_HIKE_2021_ALBUM_TOKEN,
  TEXEL_DENHELDER_2022_ALBUM_TOKEN
]
