export const MAPBOX_PUBLIC_KEY =
  'pk.eyJ1IjoibGx1biIsImEiOiJja2FqN2k2djIwNDU5MnlvNjR4YXRrMzFsIn0.Oir7SYHkVKBlgbPHldtRGQ'
export const NETHERLANDS_ALBUM_TOKEN = 'B125ON9t3mbLNC'
export const SINGAPORE_ALBUM_TOKEN = 'B12GqkRUiGojvkQ'

export const APENHEUL_ALBUM_TOKEN = 'B12Gf693ZB46qE'
export const KEUKENHOF_ALBUM_TOKEN = 'B12JEsNWnGLyCMW'

export const ALLOW_TOKEN_IDS = [
  NETHERLANDS_ALBUM_TOKEN,
  SINGAPORE_ALBUM_TOKEN,
  APENHEUL_ALBUM_TOKEN,
  KEUKENHOF_ALBUM_TOKEN
]
